name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Get LLVM
      run: |
        pip download mlir -f https://makslevental.github.io/wheels
        unzip -q mlir-*.whl
        echo "LLVM_INSTALL_DIR=$PWD/mlir" >> $GITHUB_ENV

    - name: Get Jextract
      run: |
        sudo apt install -y wget
        JEXTRACT_NAME=openjdk-22-jextract+5-33_linux-x64_bin.tar.gz
        wget -q https://download.java.net/java/early_access/jextract/22/5/$JEXTRACT_NAME
        tar xf $JEXTRACT_NAME
        echo "JEXTRACT_DIR=$PWD/jextract-22" >> $GITHUB_ENV

    - name: Generate bindings
      run: |
        ./scripts/jextract.sh

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: build/libs
